### ISSUE TITLE
There is no site.js file in wwwroot/js directory

### ISSUE THREAD

**Issue by Stringls** [psp87/Chess#30]
I've run into a problem. When I build an app by this command "dotnet build --configuration Release" I got this warn "wwwroot/js/site.js was not found", but in bundleconfig.json you mention wwwroot/js/site.js like input file.
When I try to run the program there is no ouput and no listening port 8080. So how to start the app?
I am sorry if I am wrong somewhere, I would be glad if you help me to find out how to start the app correctly.
Thank you, Have a great day

**Comment by Stringls** [comment]
In launchSettings.json I've found that app works on this url http://localhost:5000. But when I run sudo ss -tlpn I've got no such port

**Comment by Stringls** [comment]
warn wwwroot/js/site.js doesnt have any influence on build process. The problem was in my parameters of connection string. I used connection string for Windows while I was using Centos 7.
After correct build and run process I've run into problem that dotnet says my machine started listening on port 5000 but for real it doesn't. I don't know why. So the correct way to start your application Chess is to run this command with such variale
_**dotnet run --urls=http://0.0.0.0:5000**_
In this way your machine starts listening on port 5000 and your application successfully started

**Comment by psp87** [comment]
Hi @Stringls,

Sorry for not replying you, but I planned to see the issue on weekend.
I'm glad to hear that you managed to fix it. Yes, site.js doesn't have influence and will be removed. It is left over from the project template.

About the issue with listening on 5000. I suppose something should be specified for the linux environment in launchSettings.json. 
Thank you for sharing the solution.

Regards,
Plamen Petrov

**Comment by Stringls** [comment]
Hello @psp87,

I figured out what the problem was with listening on 5000. I ran the project on a vagrant (virtual) machine, but tried to access the site on the host machine, while launchSettings.json contains http://**localhost**:5000

After a little change from http://localhost:5000 to http://0.0.0.0:5000 (and _https_ too) everything works properly.
Therefore, anyone who has encountered the same problem, read about the difference between 127.0.0.1 and 0.0.0.0, it will be useful for you.

**Comment by psp87** [comment]
Hi, not sure about this one. I was intending, but didn't manage to do it. The link you found in **game.js** connects the client with the server about SignalR communication. But if you want to decouple BE and FE, I think there is a lot more to do. You should expose an WEBApi to separate the BE part in separate image. Everything specific for the client is in other other and communicate with the WEBApi on endpoints exposed. Interesting think to do, but it's not an easy task to do.
