### ISSUE TITLE
Azure SqlException: Database on server is not currently available

### ISSUE THREAD

**Issue by Stringls** [psp87/Chess#31]
![image](https://user-images.githubusercontent.com/67638547/173127131-d8a46bfc-70c5-482b-a3c0-8d26f8d44b8a.png)

Hey @psp87, A few days ago I faced such a problem (check the screenshot) and after searching the solution I've changed this function in Startup.cs
```
        private void AddDatabase(IServiceCollection services)
        {
            services.AddDbContext<ChessDbContext>(options => options.UseSqlServer(
                    this.configuration.GetChessDbConnectionString(),
                    options => options.EnableRetryOnFailure()));
        }
```
After running the github action looks like everything works well.

Also I created some terraform configuration files, so if you don't mind to add them to your repository (of course after your detailed validation :), I will be glad to send it to you).

Thank you

**Comment by psp87** [comment]
Hi @Stringl, off course you are welcome to contribute to the project :) Send me a PR and I will review it when I have time. Thank you for your interest to contribute!
